version: '3.10'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./app/node_modules
      - ./:/var/www/html/app/

  tests:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/node_modules
      - ./:/var/www/html/testing/
    command: >
      sh -c "npm run test && npm run lint"